# Generated by Django 5.1.1 on 2024-10-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
